In [6]:
import pandas as pd 
ca= pd.read_csv('data/happiness_data_ca.txt')
mx= pd.read_csv('data/happiness_data_mx.txt')
us= pd.read_csv('data/happiness_data_us.txt')
cr= pd.read_csv('data/happiness_data_cr.txt')

In [7]:
ca.head(2)

,nombre del país,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Costa Rica,2006,7.082465,0.936938,0.882420,68.559998
1,Costa Rica,2007,7.432132,0.917678,0.922736,68.720001

In [8]:
mx.head(2)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Mexico,2005,6.580658,0.902808,0.813745,64.400002
1,Mexico,2007,6.525378,0.878806,0.670430,64.680000

In [9]:
us.head(2)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices
0,United States,2006,7.181794,0.964572,0.911496
1,United States,2007,7.512688,NaN,0.871904

In [10]:
cr.head(2)

,nombre del país,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Costa Rica,2006,7.082465,0.936938,0.882420,68.559998
1,Costa Rica,2007,7.432132,0.917678,0.922736,68.720001

In [17]:
pd.concat([ca,mx,us,cr.rename(columns={'nombre del país':'country_name'})]).head().reset_index(drop=True)

,index,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,4,Canada,2010,7.650346,0.953765,0.933949,70.800003

In [18]:
sales_may= pd.read_excel('data/Sales Tables.xlsx', sheet_name=0)
sales_june= pd.read_excel('data/Sales Tables.xlsx', sheet_name=1)
regions= pd.read_excel('data/Sales Tables.xlsx', sheet_name=2)

In [19]:
sales_may

        date  store  sales
0 2022-05-01      1    341
1 2022-05-01      2    291
2 2022-05-01      3    493
3 2022-05-01      4    428
4 2022-05-01      5    152

In [20]:
regions

   store region
0      2  North
1      3   East
2      4   West
3      8  South

In [26]:
sales_may.merge(regions)

        date  store  sales region
0 2022-05-01      2    291  North
1 2022-05-01      3    493   East
2 2022-05-01      4    428   West

In [29]:
sales_may.merge(regions, how='left', on='store')

        date  store  sales region
0 2022-05-01      1    341    NaN
1 2022-05-01      2    291  North
2 2022-05-01      3    493   East
3 2022-05-01      4    428   West
4 2022-05-01      5    152    NaN