In [1]:
import pandas as pd 
ca= pd.read_csv('data/happiness_data_ca.txt')
mx= pd.read_csv('data/happiness_data_mx.txt')
us= pd.read_csv('data/happiness_data_us.txt')
cr= pd.read_csv('data/happiness_data_cr.txt')

In [2]:
ca.head(2)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003

In [3]:
mx.head(2)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Mexico,2005,6.580658,0.902808,0.813745,64.400002
1,Mexico,2007,6.525378,0.878806,0.670430,64.680000

In [4]:
us.head(2)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices
0,United States,2006,7.181794,0.964572,0.911496
1,United States,2007,7.512688,NaN,0.871904

In [5]:
cr.head(2)

,nombre del país,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Costa Rica,2006,7.082465,0.936938,0.882420,68.559998
1,Costa Rica,2007,7.432132,0.917678,0.922736,68.720001

In [6]:
pd.concat([ca,mx,us,cr.rename(columns={'nombre del país':'country_name'})]).head().reset_index(drop=True)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,Canada,2010,7.650346,0.953765,0.933949,70.800003

In [7]:
sales_may= pd.read_excel('data/Sales Tables.xlsx', sheet_name=0)
sales_june= pd.read_excel('data/Sales Tables.xlsx', sheet_name=1)
regions= pd.read_excel('data/Sales Tables.xlsx', sheet_name=2)

In [8]:
sales_may

        date  store  sales
0 2022-05-01      1    341
1 2022-05-01      2    291
2 2022-05-01      3    493
3 2022-05-01      4    428
4 2022-05-01      5    152

In [9]:
regions

   store region
0      2  North
1      3   East
2      4   West
3      8  South

In [10]:
sales_may.merge(regions)

        date  store  sales region
0 2022-05-01      2    291  North
1 2022-05-01      3    493   East
2 2022-05-01      4    428   West

In [11]:
sales_may.merge(regions, how='left', on='store')

        date  store  sales region
0 2022-05-01      1    341    NaN
1 2022-05-01      2    291  North
2 2022-05-01      3    493   East
3 2022-05-01      4    428   West
4 2022-05-01      5    152    NaN

In [19]:
import sqlite3
conn= sqlite3.connect('data/online_shop.db')

In [25]:
transactions= pd.read_sql('SELECT * From transactions', conn)
transactions.head()

  customer  item_id purchase_date
0      Ava     1011        4/1/23
1      Ava     1014        4/1/23
2      Ava     1015       4/15/23
3      Ava     1018        5/1/23
4      Ben     2345       4/15/23

In [22]:
#view the items table
items= pd.read_sql('SELECT * FROM items', conn)
items.head()

   item_id item_description    price       category rating
0     1011            Paint  $15.99   Arts & Crafts    3.5
1     1012          Crayons   $2.87   Arts & Crafts    4.7
2     1013          Markers   $2.50   Arts & Crafts    4.8
3     1014            Brush   $1.99   Arts & Crafts    4.2
4     1015            Paper  $22.49   Arts & Crafts    4.5

In [28]:
#merge two tables together 
df= transactions.merge(items, how='left', on='item_id')
df

,customer,item_id,purchase_date,item_description,price,category,rating
0,Ava,1011,4/1/23,Paint,$15.99,Arts & Crafts,3.5
1,Ava,1014,4/1/23,Brush,$1.99,Arts & Crafts,4.2
2,Ava,1015,4/15/23,Paper,$22.49,Arts & Crafts,4.5
3,Ava,1018,5/1/23,Scissors,$3.50,Arts & Crafts,4.6
4,Ben,2345,4/15/23,Dog Food,$29.99,Pet Supplies,4.9
...,...,...,...,...,...,...,...
105,Jenny,1011,4/20/23,Paint,$15.99,Arts & Crafts,3.5
106,Jenny,1014,4/20/23,Brush,$1.99,Arts & Crafts,4.2
107,Jenny,1018,4/20/23,Scissors,$3.50,Arts & Crafts,4.6
108,Jenny,1012,4/20/23,Crayons,$2.87,Arts & Crafts,4.7
109,Jenny,1015,4/20/23,Paper,$22.49,Arts & Crafts,4.5

In [29]:
#prepaaring rows for modelling

In [30]:
df.dtypes

customer            object
item_id              int64
purchase_date       object
item_description    object
price               object
category            object
rating              object
dtype: object

In [43]:
df.purchase_date= pd.to_datetime(df.purchase_date)
df.price= pd.to_numeric(df.price.astype(str).str.replace('$',''))
df.rating= pd.to_numeric(df.rating)

In [44]:
df.dtypes

customer                    object
item_id                      int64
purchase_date       datetime64[ns]
item_description            object
price                      float64
category                    object
rating                     float64
dtype: object

In [50]:
df_april_may = df[df['purchase_date'].dt.month < 6]
df_april_may.head()

,customer,item_id,purchase_date,item_description,price,category,rating
0,Ava,1011,2023-04-01,Paint,15.99,Arts & Crafts,3.5
1,Ava,1014,2023-04-01,Brush,1.99,Arts & Crafts,4.2
2,Ava,1015,2023-04-15,Paper,22.49,Arts & Crafts,4.5
3,Ava,1018,2023-05-01,Scissors,3.50,Arts & Crafts,4.6
4,Ben,2345,2023-04-15,Dog Food,29.99,Pet Supplies,4.9

In [51]:
df_june = df[df['purchase_date'].dt.month == 6]
df_june.head()

,customer,item_id,purchase_date,item_description,price,category,rating
6,Ben,2345,2023-06-15,Dog Food,29.99,Pet Supplies,4.9
12,Chloe,2345,2023-06-06,Dog Food,29.99,Pet Supplies,4.9
24,Blake,2545,2023-06-10,Cat Food,25.55,Pet Supplies,4.2
34,Maxwell,5674,2023-06-02,Video Game,30.99,Games & Toys,4.1
36,Isabel,3811,2023-06-15,Socks,7.50,Apparel,3.7

In [54]:
dog_food_rows= df_june[df_june.item_description == 'Dog Food']
june_dog_food_purchases= (dog_food_rows.groupby('customer')['item_id'].count().rename('june_dog_food_purchases'))
june_dog_food_purchases

customer
Aiden     1
Ben       1
Calvin    1
Chloe     1
Lia       1
Lily      1
Olivia    1
Name: june_dog_food_purchases, dtype: int64

In [55]:
df_june.head()

,customer,item_id,purchase_date,item_description,price,category,rating
6,Ben,2345,2023-06-15,Dog Food,29.99,Pet Supplies,4.9
12,Chloe,2345,2023-06-06,Dog Food,29.99,Pet Supplies,4.9
24,Blake,2545,2023-06-10,Cat Food,25.55,Pet Supplies,4.2
34,Maxwell,5674,2023-06-02,Video Game,30.99,Games & Toys,4.1
36,Isabel,3811,2023-06-15,Socks,7.50,Apparel,3.7